version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: scrapenstein
      POSTGRES_USER: scrapenstein
      POSTGRES_DB: scrapenstein
    volumes:
    - ./.compose/pgdata:/var/lib/postgresql/
    ports:
      - 5432:5432
